app:
  name: Plataforma GT - Gio
  version: @SED_VERSION
logger:
  level: debug
  encoding: console
http:
  enabled: true
  port: 8080
db:
  enabled: true
  type: postgres
  showsql: true
  schema: gio
  connectionstring: "postgresql+psycopg2://@DB_USERNAME:@DB_PASSWORD@plataformagt-db.cm90sapdvq98.sa-east-1.rds.amazonaws.com:5432/plataformagt"
qdrant:
  qdrantclient: "http://qdrant-service:6333"
kafka:
  brokersurls: kafka.plataformagt.internal:9092
  topic:
    queuesendingmessages: "queue-sending-messages"
    sendswarmcontactgio: "enviar-enxame-contato-gio"
    dialoguesswarmgio: "dialogos-enxame-gio"
redis:
  host: redis-master
  port: 6379
  db: 0
minio:
  host: minio.plataformagt.internal:9000
  accesskeyid: @MINIO_ACCESS_KEY
  secretaccesskey: @MINIO_SECRET_KEY
  usessl: false
security:
  enabled: true
  clientid: @SSO_CLIENTID
  clientsecret: @SSO_CLIENTSECRET
  tokenuri: https://sso-plataformagt.gtgroup.tech/realms/plataformagt/protocol/openid-connect/token
  jwkuri: https://sso-plataformagt.gtgroup.tech/realms/plataformagt/protocol/openid-connect/certs
api:
  mensageriaurl: http://mensageria-service/api
  administrativourl: http://administrativo-service/api
  projetourl: http://projeto-service/api
  authmanagerurl: http://authmanager-service/api/v1
  whatsappurl: https://graph.facebook.com/v20.0
whatsapp:
  token: EAAWvBrSNZBloBO3WKxDRq1ZBuhSMxXRAQ0ZAoWr1BI2IJ7fMXx58BxFMf2la1ZCGjaXqzypgdxA9ConhUzDaesErZB3RJpgWJ1DCq9mT8n8fcnCkAeURd2VbBbvxq0tpZAbEVsOAZArd4AcRPuAOMFIYUROyk1ec96XcTxlprKlE0t3p3AUQ1fdkZCSPznCBb3ZAtAAZDZD
  phoneid: 498918989963744
  messagingproduct: whatsapp
  recipienttype: individual
  verificationtoken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
timezone:
  name: "America/Sao_Paulo"