apiVersion: v1
kind: Service
metadata:
  namespace: plataformagt
  name: qdrant-service
  labels:
    app: qdrant
spec:
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333